name=Backchannel
version=0.1.14
author=Martin Budden
maintainer=Martin Budden
sentence=Backchannel library for telemetry and PID tuning
paragraph=
category=Device Control
url=https://github.com/martinbudden/Library-Backchannel.git
architectures=*
depends=TaskBase,StabilizedVehicle,Receiver
headers=backchannel_base.h, backchannel_stabilized_vehicle.h, backchannel_task.h, backchannel_transceiver_base.h, backchannel_transceiver_espnow.h, command_packet.h, sv_telemetry.h, sv_telemetry_data.h
