name=Backchannel
version=0.0.8
author=Martin Budden
maintainer=Martin Budden
sentence=Backchannel library for telemetry and PID tuning
paragraph=
category=Device Control
url=https://github.com/martinbudden/Library-Backchannel.git
architectures=*
depends=TaskBase,StabilizedVehicle,Receiver
headers=BackchannelBase.h, BackchannelStabilizedVehicle.h, BackchannelTask.h, BackchannelTransceiverBase.h, BackchannelTransceiverESPNOW.h, CommandPacket.h
